---
# info here: https://rpmfusion.org/Configuration#Command_Line_Setup_using_rpm

- name: Add RPM Fusion repositories
  gather_facts: false
  connection: local
  hosts: localhost
  become: yes
  vars:
    rpmfusion:
      free: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm"
      nonfree: "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm"
  tasks:
  
    # The next 2 steps are needed to execute '$(rpm -E %fedora)' and get the correct Fedora release number
    - name: Get RPM Fusion free URL
      shell: echo "{{ rpmfusion.free }}"
      register: rpmfusion_free

    - name: Get RPM Fusion nonfree URL
      shell: echo "{{ rpmfusion.nonfree }}"
      register: rpmfusion_nonfree

    - name: Set correct RPM Fusion free URL
      set_fact:
        rpmfusion_free: "{{ rpmfusion_free.stdout }}"

    - name: Set correct RPM Fusion nonfree URL
      set_fact:
        rpmfusion_nonfree: "{{ rpmfusion_nonfree.stdout }}"

    - name: Show RPM Fusion URLs
      debug:
        msg: 
          - "free    {{ rpmfusion_free }}"
          - "nonfree {{ rpmfusion_nonfree }}"

    - name: Adding RPM Fusion repositories using DNF
      ansible.builtin.dnf:
        state: latest
        name: 
          - "{{ rpmfusion_free }}"
          - "{{ rpmfusion_nonfree }}"
