---

- name: Add COPR repositories
  gather_facts: false
  connection: local
  hosts: localhost
  become: yes
  vars:
    file: repos_copr.txt
  tasks:

    - name: Adding COPR repositories
      community.general.copr:
        state: enabled
        chroot: fedora-rawhide-x86_64
        name: "{{ item }}"
      loop: "{{ lookup('file', file).splitlines() }}"
