---

- name: Install GitHub repos/packages
  gather_facts: false
  connection: local
  hosts: localhost
  vars:
    csv_file: 'packages_git_github_manero6.csv'
    clone_to_path: ~/git/github/manero6
    link_to_path: ~/bin
  tasks:
  
    - name: Get data from csv file
      read_csv:
        path: "{{ csv_file }}"
      register: csv_data

    - name: Cloning manero6 repositories
      ansible.builtin.git:
        repo: "{{ item.URL }}"
        dest: "{{ clone_to_path }}/{{ item.name }}"
        # default to 'main' if item.version was not specified in the csv file (aka if its value is None)
        #version: "{{ item.version | default('main') }}"
        version: "{{ item.version if item.version != None else 'main' }}"
      loop: "{{ csv_data.list }}"

          #- name: Creating symlink for repo "manero6/{{ item.name }}"
          #  ansible.builtin.file:
          #    src: "{{ clone_to_path }}/{{ item.name }}/{{ item.to_link }}"
          #    dest: "{{ item.link_to_path | link_to_path + '/' + item.to_link }}"
          #    state: link
          #  loop:
          #    - "{{ pizzaiuolo }}"
          #    - "{{ stuFFFinder }}"
          #    - "{{ stuFFFinder_configs }}"
