---

- name: Install dnf packages
  gather_facts: false
  connection: local
  hosts: localhost
  become: yes
  vars:
    packages: "packages_dnf.txt"
  tasks:
  
    - name: Installing dnf packages
      ansible.builtin.dnf:
        state: present
        name: "{{ lookup('file', packages).splitlines() }}"
