---

- name: Install pip packages
  gather_facts: false
  connection: local
  hosts: localhost
  vars:
    packages: "packages_pip.txt"
  tasks:
  
    - name: Installing pip packages
      ansible.builtin.pip:
        # with the following pip ignores packages already present system-wise (aka under '/usr/lib') and is able to install packages user-wise (aka under '~/.local/bin')
        extra_args: --ignore-installed
        # 'latest' (aka 'pip install -U' I suppose) instead of the default 'present' (aka 'pip install')
        state: latest
        name: "{{ lookup('file', packages).splitlines() }}"
