---

- name: Install pip packages
  gather_facts: false
  connection: local
  hosts: localhost
  vars:
    packages: "packages_pip.txt"
  tasks:
  
    - name: Installing pip packages
      ansible.builtin.pip:
        extra_args: --user
        state: present
        name: "{{ lookup('file', packages).splitlines() }}"
